#!/bin/sh
kkos=`find /opt/blcr -name blcr_imports.ko | head -1`
if test -n "$kkos"; then
  /bin/cp $kkos /lib/modules/`uname -r`/extra/
  /sbin/depmod -a
  /sbin/modprobe blcr_imports
fi
kos=`find /opt/blcr -name blcr.ko | head -1`
if test -n "$kos"; then
  /bin/cp $kos /lib/modules/`uname -r`/extra/
  /sbin/depmod -a
  /sbin/modprobe blcr
fi
